[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/tools/judgment"
  to = "/tools/request/"
  status = 301
  force = true

[[redirects]]
  from = "/tools/judgment/*"
  to = "/tools/request/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
